// <auto-generated />
using System;
using BlogSite_MVC.DATA;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlogSite_MVC.DATA.Migrations
{
    [DbContext(typeof(UygulamaDbContext))]
    partial class UygulamaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BlogSite_MVC.DATA.Gonderi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<DateTime>("DegistirilmeZamani")
                        .HasColumnType("datetime2");

                    b.Property<string>("Icerik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KategoriId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturulmaZamani")
                        .HasColumnType("datetime2");

                    b.Property<string>("Resim")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.ToTable("Gonderiler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Baslik = "Örnek Yazı 1",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(2936),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                      <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(2927)
                        },
                        new
                        {
                            Id = 2,
                            Baslik = "Örnek Yazı 2",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(2965),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                      <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(2965)
                        },
                        new
                        {
                            Id = 3,
                            Baslik = "Örnek Yazı 3",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(2968),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                      <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(2967)
                        },
                        new
                        {
                            Id = 4,
                            Baslik = "Örnek Yazı 4",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(2970),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                      <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(2969)
                        },
                        new
                        {
                            Id = 5,
                            Baslik = "Örnek Yazı 5",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(2972),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                      <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(2971)
                        },
                        new
                        {
                            Id = 6,
                            Baslik = "Örnek Yazı 6",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(2974),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                      <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(2973)
                        },
                        new
                        {
                            Id = 7,
                            Baslik = "Örnek Yazı 7",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(2975),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                      <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(2975)
                        },
                        new
                        {
                            Id = 8,
                            Baslik = "Örnek Yazı 8",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(2977),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                      <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(2977)
                        },
                        new
                        {
                            Id = 9,
                            Baslik = "Örnek Yazı 9",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(2979),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                      <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(2979)
                        },
                        new
                        {
                            Id = 10,
                            Baslik = "Örnek Yazı 10",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(2981),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                      <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(2981)
                        },
                        new
                        {
                            Id = 11,
                            Baslik = "Örnek Yazı 11",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(2983),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                      <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(2983)
                        },
                        new
                        {
                            Id = 12,
                            Baslik = "Örnek Yazı 12",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(2985),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                      <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(2985)
                        },
                        new
                        {
                            Id = 13,
                            Baslik = "Örnek Yazı 13",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(2987),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                      <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(2987)
                        },
                        new
                        {
                            Id = 14,
                            Baslik = "Örnek Yazı 14",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(3045),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                      <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(3044)
                        },
                        new
                        {
                            Id = 15,
                            Baslik = "Örnek Yazı 15",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(3047),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                      <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(3046)
                        },
                        new
                        {
                            Id = 16,
                            Baslik = "Örnek Yazı 16",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(3049),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                      <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(3049)
                        },
                        new
                        {
                            Id = 17,
                            Baslik = "Örnek Yazı 17",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(3051),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                      <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(3051)
                        },
                        new
                        {
                            Id = 18,
                            Baslik = "Örnek Yazı 18",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(3053),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                      <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(3053)
                        },
                        new
                        {
                            Id = 19,
                            Baslik = "Örnek Yazı 19",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(3055),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                      <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(3054)
                        },
                        new
                        {
                            Id = 20,
                            Baslik = "Örnek Yazı 20",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(3057),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                      <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(3056)
                        },
                        new
                        {
                            Id = 21,
                            Baslik = "Örnek Yazı 21",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(3060),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                      <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(3058)
                        },
                        new
                        {
                            Id = 22,
                            Baslik = "Örnek Yazı 22",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(3063),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                      <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(3062)
                        },
                        new
                        {
                            Id = 23,
                            Baslik = "Örnek Yazı 23",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(3065),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                      <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(3064)
                        },
                        new
                        {
                            Id = 24,
                            Baslik = "Örnek Yazı 24",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(3082),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                      <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(3066)
                        },
                        new
                        {
                            Id = 25,
                            Baslik = "Örnek Yazı 25",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(3084),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                      <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(3083)
                        },
                        new
                        {
                            Id = 26,
                            Baslik = "Örnek Yazı 26",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(3086),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                      <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(3085)
                        },
                        new
                        {
                            Id = 27,
                            Baslik = "Örnek Yazı 27",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(3088),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                      <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(3087)
                        },
                        new
                        {
                            Id = 28,
                            Baslik = "Örnek Yazı 28",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(3089),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                      <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(3089)
                        },
                        new
                        {
                            Id = 29,
                            Baslik = "Örnek Yazı 29",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(3091),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                      <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(3091)
                        },
                        new
                        {
                            Id = 30,
                            Baslik = "Örnek Yazı 30",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(3093),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                      <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(3093)
                        },
                        new
                        {
                            Id = 31,
                            Baslik = "Örnek Yazı 31",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(3095),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                      <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(3095)
                        },
                        new
                        {
                            Id = 32,
                            Baslik = "Örnek Yazı 32",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(3097),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                      <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(3097)
                        },
                        new
                        {
                            Id = 33,
                            Baslik = "Örnek Yazı 33",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(3100),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                      <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(3099)
                        },
                        new
                        {
                            Id = 34,
                            Baslik = "Örnek Yazı 34",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(3101),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                      <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(3101)
                        },
                        new
                        {
                            Id = 35,
                            Baslik = "Örnek Yazı 35",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(3103),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                      <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(3103)
                        },
                        new
                        {
                            Id = 36,
                            Baslik = "Örnek Yazı 36",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(3105),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                      <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(3105)
                        },
                        new
                        {
                            Id = 37,
                            Baslik = "Örnek Yazı 37",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(3107),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                      <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(3107)
                        },
                        new
                        {
                            Id = 38,
                            Baslik = "Örnek Yazı 38",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(3109),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                      <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(3109)
                        },
                        new
                        {
                            Id = 39,
                            Baslik = "Örnek Yazı 39",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(3111),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                      <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(3111)
                        },
                        new
                        {
                            Id = 40,
                            Baslik = "Örnek Yazı 40",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(3113),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                      <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(3112)
                        },
                        new
                        {
                            Id = 41,
                            Baslik = "Örnek Yazı 41",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(3115),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                      <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(3114)
                        },
                        new
                        {
                            Id = 42,
                            Baslik = "Örnek Yazı 42",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(3117),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                      <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(3116)
                        },
                        new
                        {
                            Id = 43,
                            Baslik = "Örnek Yazı 43",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(3119),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                      <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(3118)
                        },
                        new
                        {
                            Id = 44,
                            Baslik = "Örnek Yazı 44",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(3120),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                      <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(3120)
                        },
                        new
                        {
                            Id = 45,
                            Baslik = "Örnek Yazı 45",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(3122),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                      <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(3122)
                        },
                        new
                        {
                            Id = 46,
                            Baslik = "Örnek Yazı 46",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(3124),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                      <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(3124)
                        },
                        new
                        {
                            Id = 47,
                            Baslik = "Örnek Yazı 47",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(3126),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                      <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(3126)
                        },
                        new
                        {
                            Id = 48,
                            Baslik = "Örnek Yazı 48",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(3128),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                      <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 15, 36, 594, DateTimeKind.Local).AddTicks(3127)
                        });
                });

            modelBuilder.Entity("BlogSite_MVC.DATA.Kategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Kategoriler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Genel"
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Gezilerim"
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Mutfağım"
                        },
                        new
                        {
                            Id = 4,
                            Ad = "İş Dünyam"
                        });
                });

            modelBuilder.Entity("BlogSite_MVC.DATA.Gonderi", b =>
                {
                    b.HasOne("BlogSite_MVC.DATA.Kategori", "Kategori")
                        .WithMany("Gonderiler")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("BlogSite_MVC.DATA.Kategori", b =>
                {
                    b.Navigation("Gonderiler");
                });
#pragma warning restore 612, 618
        }
    }
}
